async function createJxlModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa="./this.program",ba=import.meta.url,ca="",da,ea;try{ca=(new URL(".",ba)).href}catch{}ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),p,ha=!1;class ia{}class ja extends ia{}var ka,la,ma=!1;
function na(){var a=oa.buffer;q=new Int8Array(a);y=new Int16Array(a);z=new Uint8Array(a);A=new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);pa=new Float32Array(a);qa=new Float64Array(a);F=new BigInt64Array(a);ra=new BigUint64Array(a)}function sa(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");la?.(a);throw a;}var ta;
async function ua(a){if(!p)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==ta&&p)a=new Uint8Array(p);else if(ea)a=ea(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(a){var b=ta;if(!p)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return va(b,a)}var y,D,F,q,pa,qa,A,E,ra,z,xa=a=>{for(;a.length>0;)a.shift()(h)},ya=[],za=[],Aa=()=>{var a=h.preRun.shift();za.push(a)};class Ba{constructor(a){this.va=a-24}init(a,b){E[this.va+16>>2]=0;E[this.va+4>>2]=a;E[this.va+8>>2]=b}}
var Ca=0,G=()=>{var a=D[+Da>>2];Da+=4;return a},Ea=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Fa=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Ea(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ga=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,
-1);return a+b},Ia=()=>a=>(crypto.getRandomValues(a),0),Ja=a=>(Ja=Ia())(a),Ka=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Ea(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},La=globalThis.TextDecoder&&new TextDecoder,Ma=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},H=(a,b=0,c,d)=>{c=Ma(a,b,c,d);if(c-b>
16&&a.buffer&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Na=[],Oa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=
3}return b},I=(a,b,c)=>{var d=z;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Pa=[];function Qa(a,b){Pa[a]={input:[],output:[],ia:b};Ra(a,Sa)}
var Sa={open(a){var b=Pa[a.node.pa];if(!b)throw new J(43);a.V=b;a.seekable=!1},close(a){a.V.ia.sa(a.V)},sa(a){a.V.ia.sa(a.V)},read(a,b,c,d){if(!a.V||!a.V.ia.Ea)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.V.ia.Ea(a.V)}catch(l){throw new J(29);}if(g===void 0&&e===0)throw new J(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.ka=Date.now());return e},write(a,b,c,d){if(!a.V||!a.V.ia.Aa)throw new J(60);try{for(var e=0;e<d;e++)a.V.ia.Aa(a.V,b[c+e])}catch(f){throw new J(29);}d&&(a.node.$=
a.node.X=Date.now());return e}},Ta={Ea(){return Na.length?Na.shift():null},Aa(a,b){b===null||b===10?(fa(H(a.output)),a.output=[]):b!=0&&a.output.push(b)},sa(a){a.output?.length>0&&(fa(H(a.output)),a.output=[])},Va(){return{fb:25856,hb:5,eb:191,gb:35387,cb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Wa(){return 0},Xa(){return[24,80]}},Ua={Aa(a,b){b===null||b===10?(k(H(a.output)),a.output=[]):b!=0&&a.output.push(b)},sa(a){a.output?.length>0&&(k(H(a.output)),a.output=
[])}},K={fa:null,ha(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new J(63);K.fa||(K.fa={dir:{node:{aa:K.S.aa,ja:K.S.ja,oa:K.S.oa,ta:K.S.ta,Ka:K.S.Ka,Ma:K.S.Ma,La:K.S.La,Ba:K.S.Ba,wa:K.S.wa},stream:{ea:K.U.ea}},file:{node:{aa:K.S.aa,ja:K.S.ja},stream:{ea:K.U.ea,read:K.U.read,write:K.U.write,Ha:K.U.Ha,Ja:K.U.Ja}},link:{node:{aa:K.S.aa,ja:K.S.ja,qa:K.S.qa},stream:{}},Da:{node:{aa:K.S.aa,ja:K.S.ja},stream:Va}});c=Wa(a,b,c,d);(c.mode&61440)===
16384?(c.S=K.fa.dir.node,c.U=K.fa.dir.stream,c.W={}):(c.mode&61440)===32768?(c.S=K.fa.file.node,c.U=K.fa.file.stream,c.Z=0,c.W=K.Qa??(K.Qa=new Uint8Array(0))):(c.mode&61440)===40960?(c.S=K.fa.link.node,c.U=K.fa.link.stream):(c.mode&61440)===8192&&(c.S=K.fa.Da.node,c.U=K.fa.Da.stream);c.ka=c.$=c.X=Date.now();a&&(a.W[b]=c,a.ka=a.$=a.X=c.ka);return c},S:{aa(a){var b={};b.Pa=(a.mode&61440)===8192?a.id:1;b.Ta=a.id;b.mode=a.mode;b.Za=1;b.uid=0;b.Ra=0;b.pa=a.pa;(a.mode&61440)===16384?b.size=4096:(a.mode&
61440)===32768?b.size=a.Z:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.ka=new Date(a.ka);b.$=new Date(a.$);b.X=new Date(a.X);b.Na=4096;b.Oa=Math.ceil(b.size/b.Na);return b},ja(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.Z!=b&&(c=a.W,a.W=new Uint8Array(b),a.W.set(c.subarray(0,Math.min(b,a.Z))),a.Z=b))},oa(){K.xa||(K.xa=new J(44),K.xa.stack="<generic error, no stack>");throw K.xa;},ta(a,b,c,d){return K.createNode(a,b,c,d)},Ka(a,b,
c){try{var d=Xa(b,c)}catch(f){}if(d){if((a.mode&61440)===16384)for(var e in d.W)throw new J(55);e=Ya(d.parent.id,d.name);if(L[e]===d)L[e]=d.na;else for(e=L[e];e;){if(e.na===d){e.na=d.na;break}e=e.na}}delete a.parent.W[a.name];b.W[c]=a;a.name=c;b.X=b.$=a.parent.X=a.parent.$=Date.now()},Ma(a,b){delete a.W[b];a.X=a.$=Date.now()},La(a,b){var c=Xa(a,b),d;for(d in c.W)throw new J(55);delete a.W[b];a.X=a.$=Date.now()},Ba(a){return[".","..",...Object.keys(a.W)]},wa(a,b,c){a=K.createNode(a,b,41471,0);a.link=
c;return a},qa(a){if((a.mode&61440)!==40960)throw new J(28);return a.link}},U:{read(a,b,c,d,e){if(e>=a.node.Z)return 0;d=Math.min(a.node.Z-e,d);b.set(a.node.W.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.$=a.X=Date.now();if(f)a.W=b.subarray(c,c+d),a.Z=d;else if(a.Z===0&&e===0)a.W=b.slice(c,c+d),a.Z=d;else{f=e+d;var g=a.W.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.W.subarray(0,a.Z),a.W=new Uint8Array(f),
a.W.set(g));a.W.set(b.subarray(c,c+d),e);a.Z=Math.max(a.Z,e+d)}return d},ea(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.Z);if(b<0)throw new J(28);return b},Ha(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new J(43);a=a.node.W;if(e&2||a.buffer!==q.buffer){d=!0;sa();e=void 0;if(!e)throw new J(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);q.set(a,e)}}else d=!1,e=a.byteOffset;return{va:e,bb:d}},Ja(a,b,c,d){K.U.write(a,
b,0,d,c,!1);return 0}}},Za=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},$a=null,ab={},M=[],bb=1,L=null,cb=!1,db=!0,J=class{name="ErrnoError";constructor(a){this.da=a}},eb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},fb=class{S={};U={};ua=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ha=a.ha;this.id=bb++;this.name=b;this.mode=c;this.pa=d;this.ka=this.$=
this.X=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}};
function N(a,b={}){if(!a)throw new J(44);b.ya??(b.ya=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(l=>!!l);for(var d=$a,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Ga(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Fa(e+"/"+a[f]);try{d=Xa(d,a[f])}catch(l){if(l?.da===44&&g&&b.$a)return{path:e};throw l;}!d.ua||g&&!b.ya||(d=d.ua.root);if((d.mode&61440)===40960&&(!g||b.ra)){if(!d.S.qa)throw new J(52);
d=d.S.qa(d);d.charAt(0)==="/"||(d=Ga(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new J(32);}function Ya(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%L.length}function Xa(a,b){var c=(a.mode&61440)===16384?(c=gb(a,"x"))?c:a.S.oa?0:2:54;if(c)throw new J(c);for(c=L[Ya(a.id,b)];c;c=c.na){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.S.oa(a,b)}
function Wa(a,b,c,d){a=new fb(a,b,c,d);b=Ya(a.parent.id,a.name);a.na=L[b];return L[b]=a}function gb(a,b){return db?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function hb(a,b){if((a.mode&61440)!==16384)return 54;try{return Xa(a,b),20}catch(c){}return gb(a,"wx")}function ib(a){if(!a)throw new J(63);return a}function O(a){a=M[a];if(!a)throw new J(8);return a}
function jb(a,b=-1){a=Object.assign(new eb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!M[b])break a;throw new J(33);}a.la=b;return M[b]=a}function kb(a,b=-1){a=jb(a,b);a.U?.jb?.(a);return a}function lb(a,b){var c=void 0,d=c?null:a;c??=a.S.ja;ib(c);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new J(22);throw e;}}var Va={open(a){a.U=ab[a.node.pa].U;a.U.open?.(a)},ea(){throw new J(70);}};function Ra(a,b){ab[a]={U:b}}
function mb(a,b){var c=b==="/";if(c&&$a)throw new J(10);if(!c&&b){var d=N(b,{ya:!1});b=d.path;d=d.node;if(d.ua)throw new J(10);if((d.mode&61440)!==16384)throw new J(54);}b={type:a,kb:{},Ia:b,Ya:[]};a=a.ha(b);a.ha=b;b.root=a;c?$a=a:d&&(d.ua=b,d.ha&&d.ha.Ya.push(b))}function nb(a,b,c){var d=N(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new J(28);if(a==="."||a==="..")throw new J(20);var e=hb(d,a);if(e)throw new J(e);if(!d.S.ta)throw new J(63);return d.S.ta(d,a,b,c)}
function Q(a){return nb(a,16895,0)}function ob(a,b,c){typeof c=="undefined"&&(c=b,b=438);nb(a,b|8192,c)}function pb(a,b){if(!Ka(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=hb(c,b);if(d)throw new J(d);if(!c.S.wa)throw new J(63);c.S.wa(c,b,a)}function qb(a,b){a=N(a,{ra:!b}).node;return ib(a.S.aa)(a)}
function rb(a,b,c=438){if(a==="")throw new J(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=N(a,{ra:!(b&131072),$a:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new J(20);}else{if(e)throw new J(31);d=nb(a,c|511,0);f=!0}if(!d)throw new J(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&(d.mode&61440)!==
16384)throw new J(54);if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=(d.mode&61440)===16384&&(e!=="r"||b&576)?31:gb(d,e)):e=44,e))throw new J(e);if(b&512&&!f){e=d;e=typeof e=="string"?N(e,{ra:!0}).node:e;if((e.mode&61440)===16384)throw new J(31);if((e.mode&61440)!==32768)throw new J(28);if(a=gb(e,"w"))throw new J(a);lb(e,{size:0,timestamp:Date.now()})}a:{for(e=d;;){if(e===e.parent){e=e.ha.Ia;var g=g?e[e.length-1]!=="/"?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:
e.name;e=e.parent}g=void 0}b=jb({node:d,path:g,flags:b&-131713,seekable:!0,position:0,U:d.U,ab:[],error:!1});b.U.open&&b.U.open(b);f&&(c&=511,d=typeof d=="string"?N(d,{ra:!0}).node:d,lb(d,{mode:c&4095|d.mode&-4096,X:Date.now(),ib:void 0}));return b}function sb(a,b,c){if(a.la===null)throw new J(8);if(!a.seekable||!a.U.ea)throw new J(70);if(c!=0&&c!=1&&c!=2)throw new J(28);a.position=a.U.ea(a,b,c);a.ab=[]}
function R(a,b,c){a=Fa("/dev/"+a);var d=Za(!!b,!!c);R.Ga??(R.Ga=64);var e=R.Ga++<<8|0;Ra(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,l,m){for(var n=0,v=0;v<m;v++){try{var x=b()}catch(r){throw new J(29);}if(x===void 0&&n===0)throw new J(6);if(x===null||x===void 0)break;n++;g[l+v]=x}n&&(f.node.ka=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{c(g[l+n])}catch(v){throw new J(29);}m&&(f.node.$=f.node.X=Date.now());return n}});ob(a,d,e)}var S={};
function tb(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":O(a).path;if(b.length==0){if(!c)throw new J(44);return a}return a+"/"+b}
function ub(a,b){E[a>>2]=b.Pa;E[a+4>>2]=b.mode;E[a+8>>2]=b.Za;E[a+12>>2]=b.uid;E[a+16>>2]=b.Ra;E[a+20>>2]=b.pa;F[a+24>>3]=BigInt(b.size);D[a+32>>2]=4096;D[a+36>>2]=b.Oa;var c=b.ka.getTime(),d=b.$.getTime(),e=b.X.getTime();F[a+40>>3]=BigInt(Math.floor(c/1E3));E[a+48>>2]=c%1E3*1E3*1E3;F[a+56>>3]=BigInt(Math.floor(d/1E3));E[a+64>>2]=d%1E3*1E3*1E3;F[a+72>>3]=BigInt(Math.floor(e/1E3));E[a+80>>2]=e%1E3*1E3*1E3;F[a+88>>3]=BigInt(b.Ta);return 0}
var Da=void 0,T=a=>{for(var b="";;){var c=z[a++];if(!c)return b;b+=String.fromCharCode(c)}},U={},V={},vb={},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},wb=a=>{throw new W(a);};function xb(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(V.hasOwnProperty(a)){if(c.Sa)return;throw new W(`Cannot register type '${d}' twice`);}V[a]=b;delete vb[a];U.hasOwnProperty(a)&&(b=U[a],delete U[a],b.forEach(e=>e()))}
function X(a,b,c={}){return xb(a,b,c)}
var yb=(a,b,c)=>{switch(b){case 1:return c?d=>q[d]:d=>z[d];case 2:return c?d=>y[d>>1]:d=>A[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>F[d>>3]:d=>ra[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},zb=[],Y=[0,1,,1,null,1,!0,1,!1,1],Ab=a=>{a>9&&0===--Y[a+1]&&(Y[a]=void 0,zb.push(a))},Bb=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Y[a]},Eb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=
zb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}};function Fb(a){return this.Y(E[a>>2])}var Gb={name:"emscripten::val",Y:a=>{var b=Bb(a);Ab(a);return b},ga:(a,b)=>Eb(b),ma:Fb,ca:null},Hb=(a,b)=>{switch(b){case 4:return function(c){return this.Y(pa[c>>2])};case 8:return function(c){return this.Y(qa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ib=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Jb(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].ca===void 0)return!0;return!1}
var Kb=(a,b)=>{if(void 0===h[a].ba){var c=h[a];h[a]=function(...d){if(!h[a].ba.hasOwnProperty(d.length))throw new W(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].ba})!`);return h[a].ba[d.length].apply(this,d)};h[a].ba=[];h[a].ba[c.Ca]=c}},Lb=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].ba&&void 0!==h[a].ba[c])throw new W(`Cannot register public name '${a}' twice`);Kb(a,a);if(h[a].ba.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].ba[c]=b}else h[a]=b,h[a].Ca=c},Mb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+d*4>>2]);return c},Nb=class extends Error{constructor(a){super(a);this.name="InternalError"}},Ob=[],Qb=a=>{var b=Ob[a];b||(Ob[a]=b=Pb.get(a));return b},Rb=(a,b)=>{a=T(a);var c=Qb(b);if(typeof c!="function")throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};class Sb extends Error{}
var Ub=a=>{a=Tb(a);var b=T(a);Z(a);return b},Vb=(a,b)=>{function c(f){e[f]||V[f]||(vb[f]?vb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Sb(`${a}: `+d.map(Ub).join([", "]));},Wb=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new Nb("Mismatched type converter count");for(var m=0;m<d.length;++m)X(d[m],l[m])}var d=[];d.forEach(l=>vb[l]=a);var e=Array(a.length),f=[],g=0;for(let [l,m]of a.entries())V.hasOwnProperty(m)?e[l]=V[m]:(f.push(m),U.hasOwnProperty(m)||(U[m]=
[]),U[m].push(()=>{e[l]=V[m];++g;g===f.length&&c(e)}));0===f.length&&c(e)},Xb=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},Yb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,Zb=(a,b,c)=>{a>>=1;b=Ma(A,a,b/2,c);if(b-a>16&&Yb)return Yb.decode(A.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(A[a]);return c},$b=(a,b,c)=>{c??=2147483647;if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},ac=
a=>a.length*2,bc=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},cc=(a,b,c)=>{c??=2147483647;if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},dc=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},ec=[],fc=a=>{var b=ec.length;ec.push(a);return b},hc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=E[b+d*
4>>2],g=V[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Ub(f)}`,new W(a);c[e]=g}return c},ic=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>2]=Eb(d));return a},jc={},kc=a=>{var b=jc[a];return b===void 0?T(a):b},lc={},nc=()=>{if(!mc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:aa},b;for(b in lc)lc[b]===void 0?delete a[b]:a[b]=lc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);mc=
c}return mc},mc;L=Array(4096);mb(K,"/");Q("/tmp");Q("/home");Q("/home/web_user");(function(){Q("/dev");Ra(259,{read:()=>0,write:(d,e,f,g)=>g,ea:()=>0});ob("/dev/null",259);Qa(1280,Ta);Qa(1536,Ua);ob("/dev/tty",1280);ob("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Ja(a),b=a.byteLength);return a[--b]};R("random",c);R("urandom",c);Q("/dev/shm");Q("/dev/shm/tmp")})();
(function(){Q("/proc");var a=Q("/proc/self");Q("/proc/self/fd");mb({ha(){var b=Wa(a,"fd",16895,73);b.U={ea:K.U.ea};b.S={oa(c,d){c=+d;var e=O(c);c={parent:null,ha:{Ia:"fake"},S:{qa:()=>e.path},id:c+1};return c.parent=c},Ba(){return Array.from(M.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(p=h.wasmBinary);h.thisProgram&&(aa=h.thisProgram);
if(h.preInit)for(typeof h.preInit=="function"&&(h.preInit=[h.preInit]);h.preInit.length>0;)h.preInit.shift()();
var Tb,oc,Z,pc,qc,rc,oa,Pb,uc={i:(a,b,c)=>{(new Ba(a)).init(b,c);Ca++;sa()},o:function(a,b,c){Da=c;try{var d=O(a);switch(b){case 0:var e=G();if(e<0)break;for(;M[e];)e++;return kb(d,e).la;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=G(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=G(),y[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof S=="undefined"||f.name!=="ErrnoError")throw f;return-f.da}},A:function(a,b){try{var c=O(a),d=c.node,e=c.U.aa;a=e?c:d;e??=d.S.aa;
ib(e);var f=e(a);return ub(b,f)}catch(g){if(typeof S=="undefined"||g.name!=="ErrnoError")throw g;return-g.da}},C:function(a,b,c){Da=c;try{var d=O(a);switch(b){case 21509:return d.V?0:-59;case 21505:if(!d.V)return-59;if(d.V.ia.Va){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=G();D[e>>2]=25856;D[e+4>>2]=5;D[e+8>>2]=191;D[e+12>>2]=35387;for(var f=0;f<32;f++)q[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.V?0:-59;case 21506:case 21507:case 21508:if(!d.V)return-59;
if(d.V.ia.Wa)for(e=G(),a=[],f=0;f<32;f++)a.push(q[e+f+17]);return 0;case 21519:if(!d.V)return-59;e=G();return D[e>>2]=0;case 21520:return d.V?-28:-59;case 21537:case 21531:e=G();if(!d.U.Ua)throw new J(59);return d.U.Ua(d,b,e);case 21523:if(!d.V)return-59;d.V.ia.Xa&&(f=[24,80],e=G(),y[e>>1]=f[0],y[e+2>>1]=f[1]);return 0;case 21524:return d.V?0:-59;case 21515:return d.V?0:-59;default:return-28}}catch(g){if(typeof S=="undefined"||g.name!=="ErrnoError")throw g;return-g.da}},z:function(a,b,c,d){try{b=
b?H(z,b):"";var e=d&256;b=tb(a,b,d&4096);return ub(c,e?qb(b,!0):qb(b))}catch(f){if(typeof S=="undefined"||f.name!=="ErrnoError")throw f;return-f.da}},D:function(a,b,c,d){Da=d;try{b=b?H(z,b):"";b=tb(a,b);var e=d?G():0;c&64&&(e&=-19);return rb(b,c,e).la}catch(f){if(typeof S=="undefined"||f.name!=="ErrnoError")throw f;return-f.da}},E:()=>sa(""),r:(a,b,c,d,e)=>{b=T(b);d=d===0n;var f=g=>g;if(d){let g=c*8;f=l=>BigInt.asUintN(g,l);e=f(e)}X(a,{name:b,Y:f,ga:(g,l)=>{typeof l=="number"&&(l=BigInt(l));return l},
ma:yb(b,c,!d),ca:null})},I:(a,b,c,d)=>{b=T(b);X(a,{name:b,Y:function(e){return!!e},ga:function(e,f){return f?c:d},ma:function(e){return this.Y(z[e])},ca:null})},G:a=>X(a,Gb),q:(a,b,c)=>{b=T(b);X(a,{name:b,Y:d=>d,ga:(d,e)=>e,ma:Hb(b,c),ca:null})},h:(a,b,c,d,e,f,g)=>{var l=Mb(b,c);a=T(a);a=Xb(a);e=Rb(d,e);Lb(a,function(){Vb(`Cannot call ${a} due to unbound types`,l)},b-1);Wb(l,m=>{var n=a;var v=a;m=[m[0],null].concat(m.slice(1));var x=e,r=m.length;if(r<2)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");
var B=m[1]!==null&&!1,C=Jb(m),P=!m[0].Fa,t=m[0],w=m[1];x=[v,wb,x,f,Ib,t.Y.bind(t),w?.ga.bind(w)];for(t=2;t<r;++t)w=m[t],x.push(w.ga.bind(w));if(!C)for(t=B?1:2;t<m.length;++t)m[t].ca!==null&&x.push(m[t].ca);C=Jb(m);t=m.length-2;var u=[];w=["fn"];B&&w.push("thisWired");for(r=0;r<t;++r)u.push(`arg${r}`),w.push(`arg${r}Wired`);u=u.join(",");w=w.join(",");u=`return function (${u}) {\n`;C&&(u+="var destructors = [];\n");var Cb=C?"destructors":"null",Ha="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");
B&&(u+=`var thisWired = toClassParamWire(${Cb}, this);\n`);for(r=0;r<t;++r){var Db=`toArg${r}Wire`;u+=`var arg${r}Wired = ${Db}(${Cb}, arg${r});\n`;Ha.push(Db)}u+=(P||g?"var rv = ":"")+`invoker(${w});\n`;if(C)u+="runDestructors(destructors);\n";else for(r=B?1:2;r<m.length;++r)B=r===1?"thisWired":"arg"+(r-2)+"Wired",m[r].ca!==null&&(u+=`${B}_dtor(${B});\n`,Ha.push(`${B}_dtor`));P&&(u+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(Ha,u+"}\n"))(...x);v=Object.defineProperty(m,"name",{value:v});
m=b-1;if(!h.hasOwnProperty(n))throw new Nb("Replacing nonexistent public symbol");void 0!==h[n].ba&&void 0!==m?h[n].ba[m]=v:(h[n]=v,h[n].Ca=m);return[]})},b:(a,b,c,d,e)=>{b=T(b);var f=l=>l;if(d===0){var g=32-8*c;f=l=>l<<g>>>g;e=f(e)}X(a,{name:b,Y:f,ga:(l,m)=>m,ma:yb(b,c,d!==0),ca:null})},a:(a,b,c)=>{function d(f){return new e(q.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=T(c);X(a,{name:c,
Y:d,ma:d},{Sa:!0})},H:(a,b)=>{b=T(b);X(a,{name:b,Y(c){var d=(d=c+4)?H(z,d,E[c>>2],!0):"";Z(c);return d},ga(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e=typeof d=="string";if(!(e||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new W("Cannot pass non-string to std::string");var f=e?Oa(d):d.length;var g=oc(4+f+1),l=g+4;E[g>>2]=f;e?I(d,l,f+1):z.set(d,l);c!==null&&c.push(Z,g);return g},ma:Fb,ca(c){Z(c)}})},j:(a,b,c)=>{c=T(c);if(b===2){var d=Zb;var e=$b;var f=ac}else d=bc,e=cc,f=dc;
X(a,{name:c,Y:g=>{var l=d(g+4,E[g>>2]*b,!0);Z(g);return l},ga:(g,l)=>{if(typeof l!="string")throw new W(`Cannot pass non-string to C++ string type ${c}`);var m=f(l),n=oc(4+m+b);E[n>>2]=m/b;e(l,n+4,m+b);g!==null&&g.push(Z,n);return n},ma:Fb,ca(g){Z(g)}})},s:(a,b)=>{b=T(b);X(a,{Fa:!0,name:b,Y:()=>{},ga:()=>{}})},v:()=>{throw new ja;},f:(a,b,c)=>{var d;[b,...d]=hc(a,b);var e=b.ga.bind(b),f=d.map(m=>m.ma.bind(m));a--;var g={toValue:Bb};a=f.map((m,n)=>{var v=`argFromPtr${n}`;g[v]=m;return`${v}(args${n?
"+"+n*8:""})`});switch(c){case 0:var l="toValue(handle)";break;case 2:l="new (toValue(handle))";break;case 3:l="";break;case 1:g.getStringOrSymbol=kc,l="toValue(handle)[getStringOrSymbol(methodName)]"}l+=`(${a})`;b.Fa||(g.toReturnWire=e,g.emval_returnValue=ic,l=`return emval_returnValue(toReturnWire, destructorsRef, ${l})`);l=`return function (handle, methodName, destructorsRef, args) {\n${l}\n}`;c=(new Function(Object.keys(g),l))(...Object.values(g));b=`methodCaller<(${d.map(m=>m.name)}) => ${b.name}>`;
return fc(Object.defineProperty(c,"name",{value:b}))},g:Ab,l:(a,b)=>{a=Bb(a);b=Bb(b);return Eb(a[b])},k:a=>{a>9&&(Y[a+1]+=1)},e:(a,b,c,d,e)=>ec[a](b,c,d,e),c:a=>Eb(kc(a)),d:a=>{var b=Bb(a);Ib(b);Ab(a)},x:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=Math.max(f,e)*60;D[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=
b(f);b=b(e);e<f?(I(a,c,17),I(b,d,17)):(I(a,d,17),I(b,c,17))},w:a=>{var b=z.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);na();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:(a,b)=>{var c=0,d=0,e;for(e of nc()){var f=b+c;E[a+d>>2]=f;c+=I(e,f,Infinity)+1;d+=4}return 0},u:(a,b)=>{var c=nc();E[a>>2]=c.length;a=0;for(var d of c)a+=
Oa(d)+1;E[b>>2]=a;return 0},m:function(a){try{var b=O(a);if(b.la===null)throw new J(8);b.za&&(b.za=null);try{b.U.close&&b.U.close(b)}catch(c){throw c;}finally{M[b.la]=null}b.la=null;return 0}catch(c){if(typeof S=="undefined"||c.name!=="ErrnoError")throw c;return c.da}},B:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var l=E[a>>2],m=E[a+4>>2];a+=8;var n=e,v=l,x=m,r=f,B=q;if(x<0||r<0)throw new J(28);if(n.la===null)throw new J(8);if((n.flags&2097155)===1)throw new J(8);if((n.node.mode&
61440)===16384)throw new J(31);if(!n.U.read)throw new J(28);var C=typeof r!="undefined";if(!C)r=n.position;else if(!n.seekable)throw new J(70);var P=n.U.read(n,B,v,x,r);C||(n.position+=P);var t=P;if(t<0){var w=-1;break a}b+=t;if(t<m)break;typeof f!="undefined"&&(f+=t)}w=b}E[d>>2]=w;return 0}catch(u){if(typeof S=="undefined"||u.name!=="ErrnoError")throw u;return u.da}},y:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=O(a);sb(e,b,c);F[d>>3]=
BigInt(e.position);e.za&&b===0&&c===0&&(e.za=null);return 0}catch(f){if(typeof S=="undefined"||f.name!=="ErrnoError")throw f;return f.da}},n:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var f,g=b=0;g<c;g++){var l=E[a>>2],m=E[a+4>>2];a+=8;var n=e,v=l,x=m,r=f,B=q;if(x<0||r<0)throw new J(28);if(n.la===null)throw new J(8);if((n.flags&2097155)===0)throw new J(8);if((n.node.mode&61440)===16384)throw new J(31);if(!n.U.write)throw new J(28);n.seekable&&n.flags&1024&&sb(n,0,2);var C=typeof r!="undefined";if(!C)r=
n.position;else if(!n.seekable)throw new J(70);var P=n.U.write(n,B,v,x,r,void 0);C||(n.position+=P);var t=P;if(t<0){var w=-1;break a}b+=t;if(t<m)break;typeof f!="undefined"&&(f+=t)}w=b}E[d>>2]=w;return 0}catch(u){if(typeof S=="undefined"||u.name!=="ErrnoError")throw u;return u.da}},p:sc,F:tc};function sc(a,b,c){var d=rc();try{return Qb(a)(b,c)}catch(e){qc(d);if(!(e instanceof ia))throw e;pc(1,0)}}function tc(a,b,c){var d=rc();try{Qb(a)(b,c)}catch(e){qc(d);if(!(e instanceof ia))throw e;pc(1,0)}}var vc;
vc=await (async function(){function a(c){c=vc=c.exports;Tb=c.L;oc=c.N;Z=c.O;h._main=c.P;pc=c.Q;qc=c.R;rc=c.T;oa=c.J;Pb=c.M;na();return vc}var b={a:uc};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=h.locateFile?h.locateFile?h.locateFile("jxl.wasm",ca):ca+"jxl.wasm":(new URL("jxl.wasm",import.meta.url)).href;return function(c){return a(c.instance)}(await wa(b))}());
(function(){function a(){h.calledRun=!0;if(!ha){ma=!0;if(!h.noFSInit&&!cb){var b,c;cb=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?R("stdin",b):pb("/dev/tty","/dev/stdin");c?R("stdout",null,c):pb("/dev/tty","/dev/stdout");d?R("stderr",null,d):pb("/dev/tty1","/dev/stderr");rb("/dev/stdin",0);rb("/dev/stdout",1);rb("/dev/stderr",1)}vc.K();db=!1;ka?.(h);h.onRuntimeInitialized?.();if(h.postRun)for(typeof h.postRun=="function"&&(h.postRun=[h.postRun]);h.postRun.length;){var d=h.postRun.shift();ya.push(d)}xa(ya)}}
if(h.preRun)for(typeof h.preRun=="function"&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();xa(za);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ma?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ka=a;la=b});
;return moduleRtn}export default createJxlModule;
