async function createJxlModule(moduleArg={}){var moduleRtn;var k=moduleArg,aa="./this.program",ba=import.meta.url,ca="",da,ea;try{ca=(new URL(".",ba)).href}catch{}ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),l=console.error.bind(console),p,ha=!1,ia,ja,q,y,z,A,D,E,ka,la,F,ma,na=!1;
function oa(){var a=pa.buffer;q=new Int8Array(a);z=new Int16Array(a);y=new Uint8Array(a);A=new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);ka=new Float32Array(a);la=new Float64Array(a);F=new BigInt64Array(a);ma=new BigUint64Array(a)}function qa(a){k.onAbort?.(a);a="Aborted("+a+")";l(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ja?.(a);throw a;}var ra;
async function sa(a){if(!p)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==ra&&p)a=new Uint8Array(p);else if(ea)a=ea(a);else throw"both async and sync fetching of the wasm failed";return a}async function ta(a,b){try{var c=await sa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),qa(d)}}
async function ua(a){var b=ra;if(!p)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return ta(b,a)}var va=a=>{for(;0<a.length;)a.shift()(k)},wa=[],xa=[],ya=()=>{var a=k.preRun.shift();xa.push(a)};class za{constructor(a){this.ta=a-24}}
var Aa=0,Ba=0,G=()=>{var a=D[+Ca>>2];Ca+=4;return a},Da=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Fa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Da(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ga=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.slice(0,-1);return a+b},Ha=()=>a=>crypto.getRandomValues(a),Ia=a=>{(Ia=Ha())(a)},Ja=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Da(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ka=globalThis.TextDecoder&&new TextDecoder,La=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},H=(a,b=0,c,d)=>{c=La(a,b,
c,d);if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ma=[],Na=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=
4,++c):b+=3}return b},I=(a,b,c)=>{var d=y;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Oa=[];function Pa(a,b){Oa[a]={input:[],output:[],ga:b};Qa(a,Ra)}
var Ra={open(a){var b=Oa[a.node.ma];if(!b)throw new J(43);a.T=b;a.seekable=!1},close(a){a.T.ga.qa(a.T)},qa(a){a.T.ga.qa(a.T)},read(a,b,c,d){if(!a.T||!a.T.ga.Ca)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.T.ga.Ca(a.T)}catch(h){throw new J(29);}if(void 0===g&&0===e)throw new J(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.ha=Date.now());return e},write(a,b,c,d){if(!a.T||!a.T.ga.ya)throw new J(60);try{for(var e=0;e<d;e++)a.T.ga.ya(a.T,b[c+e])}catch(f){throw new J(29);}d&&(a.node.X=
a.node.V=Date.now());return e}},Sa={Ca(){return Ma.length?Ma.shift():null},ya(a,b){null===b||10===b?(fa(H(a.output)),a.output=[]):0!=b&&a.output.push(b)},qa(a){0<a.output?.length&&(fa(H(a.output)),a.output=[])},Sa(){return{bb:25856,eb:5,ab:191,cb:35387,$a:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ta(){return 0},Ua(){return[24,80]}},Ta={ya(a,b){null===b||10===b?(l(H(a.output)),a.output=[]):0!=b&&a.output.push(b)},qa(a){0<a.output?.length&&(l(H(a.output)),a.output=
[])}},K={aa:null,fa(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.aa||(K.aa={dir:{node:{ea:K.R.ea,ba:K.R.ba,la:K.R.la,ra:K.R.ra,Ia:K.R.Ia,Ka:K.R.Ka,Ja:K.R.Ja,za:K.R.za,ua:K.R.ua},stream:{$:K.O.$}},file:{node:{ea:K.R.ea,ba:K.R.ba},stream:{$:K.O.$,read:K.O.read,write:K.O.write,Fa:K.O.Fa,Ha:K.O.Ha}},link:{node:{ea:K.R.ea,ba:K.R.ba,na:K.R.na},stream:{}},Ba:{node:{ea:K.R.ea,ba:K.R.ba},stream:Ua}});c=Va(a,b,c,d);16384===(c.mode&61440)?
(c.R=K.aa.dir.node,c.O=K.aa.dir.stream,c.S={}):32768===(c.mode&61440)?(c.R=K.aa.file.node,c.O=K.aa.file.stream,c.U=0,c.S=null):40960===(c.mode&61440)?(c.R=K.aa.link.node,c.O=K.aa.link.stream):8192===(c.mode&61440)&&(c.R=K.aa.Ba.node,c.O=K.aa.Ba.stream);c.ha=c.X=c.V=Date.now();a&&(a.S[b]=c,a.ha=a.X=a.V=c.ha);return c},hb(a){return a.S?a.S.subarray?a.S.subarray(0,a.U):new Uint8Array(a.S):new Uint8Array(0)},R:{ea(a){var b={};b.Na=8192===(a.mode&61440)?a.id:1;b.Qa=a.id;b.mode=a.mode;b.Wa=1;b.uid=0;b.Oa=
0;b.ma=a.ma;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.U:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ha=new Date(a.ha);b.X=new Date(a.X);b.V=new Date(a.V);b.La=4096;b.Ma=Math.ceil(b.size/b.La);return b},ba(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.U!=b&&(0==b?(a.S=null,a.U=0):(c=a.S,a.S=new Uint8Array(b),c&&a.S.set(c.subarray(0,Math.min(b,a.U))),a.U=b)))},la(){K.va||(K.va=new J(44),K.va.stack="<generic error, no stack>");
throw K.va;},ra(a,b,c,d){return K.createNode(a,b,c,d)},Ia(a,b,c){try{var d=Wa(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.S)throw new J(55);e=Xa(d.parent.id,d.name);if(L[e]===d)L[e]=d.ka;else for(e=L[e];e;){if(e.ka===d){e.ka=d.ka;break}e=e.ka}}delete a.parent.S[a.name];b.S[c]=a;a.name=c;b.V=b.X=a.parent.V=a.parent.X=Date.now()},Ka(a,b){delete a.S[b];a.V=a.X=Date.now()},Ja(a,b){var c=Wa(a,b),d;for(d in c.S)throw new J(55);delete a.S[b];a.V=a.X=Date.now()},za(a){return[".","..",...Object.keys(a.S)]},
ua(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},na(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},O:{read(a,b,c,d,e){var f=a.node.S;if(e>=a.node.U)return 0;a=Math.min(a.node.U-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.X=a.V=Date.now();if(b.subarray&&(!a.S||a.S.subarray)){if(f)return a.S=b.subarray(c,c+d),a.U=d;if(0===a.U&&0===e)return a.S=b.slice(c,
c+d),a.U=d;if(e+d<=a.U)return a.S.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.S?a.S.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.S,a.S=new Uint8Array(f),0<a.U&&a.S.set(g.subarray(0,a.U),0));if(a.S.subarray&&b.subarray)a.S.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.S[e+f]=b[c+f];a.U=Math.max(a.U,e+d);return d},$(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.U);if(0>b)throw new J(28);return b},Fa(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new J(43);a=a.node.S;if(e&2||!a||a.buffer!==q.buffer){d=!0;qa();e=void 0;if(!e)throw new J(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);q.set(a,e)}}else d=!1,e=a.byteOffset;return{ta:e,Za:d}},Ha(a,b,c,d){K.O.write(a,b,0,d,c,!1);return 0}}},Ya=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Za=null,$a={},M=[],ab=1,L=null,bb=!1,cb=!0,db={},J=class{name="ErrnoError";constructor(a){this.da=a}},eb=class{oa={};node=null;get flags(){return this.oa.flags}set flags(a){this.oa.flags=
a}get position(){return this.oa.position}set position(a){this.oa.position=a}},fb=class{R={};O={};sa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.fa=a.fa;this.id=ab++;this.name=b;this.mode=c;this.ma=d;this.ha=this.X=this.V=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function N(a,b={}){if(!a)throw new J(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(h=>!!h);for(var d=Za,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ga(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Fa(e+"/"+a[f]);try{d=Wa(d,a[f])}catch(h){if(44===h?.da&&g&&b.Xa)return{path:e};throw h;}!d.sa||g&&!b.wa||(d=d.sa.root);if(40960===(d.mode&61440)&&(!g||b.pa)){if(!d.R.na)throw new J(52);
d=d.R.na(d);"/"===d.charAt(0)||(d=Ga(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new J(32);}function Xa(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%L.length}function Wa(a,b){var c=16384===(a.mode&61440)?(c=gb(a,"x"))?c:a.R.la?0:2:54;if(c)throw new J(c);for(c=L[Xa(a.id,b)];c;c=c.ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.R.la(a,b)}
function Va(a,b,c,d){a=new fb(a,b,c,d);b=Xa(a.parent.id,a.name);a.ka=L[b];return L[b]=a}function hb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function gb(a,b){if(cb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ib(a,b){if(16384!==(a.mode&61440))return 54;try{return Wa(a,b),20}catch(c){}return gb(a,"wx")}function jb(a){if(!a)throw new J(63);return a}
function P(a){a=M[a];if(!a)throw new J(8);return a}function kb(a,b=-1){a=Object.assign(new eb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!M[b])break a;throw new J(33);}a.ia=b;return M[b]=a}function lb(a,b=-1){a=kb(a,b);a.O?.gb?.(a);return a}function mb(a,b){var c=null?.O.ba,d=c?null:a;c??=a.R.ba;jb(c);c(d,b)}var Ua={open(a){a.O=$a[a.node.ma].O;a.O.open?.(a)},$(){throw new J(70);}};function Qa(a,b){$a[a]={O:b}}
function nb(a,b){var c="/"===b;if(c&&Za)throw new J(10);if(!c&&b){var d=N(b,{wa:!1});b=d.path;d=d.node;if(d.sa)throw new J(10);if(16384!==(d.mode&61440))throw new J(54);}b={type:a,ib:{},Ga:b,Va:[]};a=a.fa(b);a.fa=b;b.root=a;c?Za=a:d&&(d.sa=b,d.fa&&d.fa.Va.push(b))}function ob(a,b,c){var d=N(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new J(28);if("."===a||".."===a)throw new J(20);var e=ib(d,a);if(e)throw new J(e);if(!d.R.ra)throw new J(63);return d.R.ra(d,a,b,c)}
function Q(a){return ob(a,16895,0)}function pb(a,b,c){"undefined"==typeof c&&(c=b,b=438);ob(a,b|8192,c)}function qb(a,b){if(!Ja(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=ib(c,b);if(d)throw new J(d);if(!c.R.ua)throw new J(63);c.R.ua(c,b,a)}
function rb(a,b,c=438){if(""===a)throw new J(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=N(a,{pa:!(b&131072),Xa:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new J(20);}else{if(e)throw new J(31);d=ob(a,c|511,0);f=!0}if(!d)throw new J(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new J(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==hb(b)||b&576)?31:gb(d,hb(b)):44))throw new J(e);if(b&512&&!f){e=d;e="string"==typeof e?N(e,{pa:!0}).node:e;if(16384===(e.mode&61440))throw new J(31);if(32768!==(e.mode&61440))throw new J(28);var g=gb(e,"w");if(g)throw new J(g);mb(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.fa.Ga;var h=h?"/"!==e[e.length-1]?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}h=
kb({node:d,path:h,flags:b,seekable:!0,position:0,O:d.O,Ya:[],error:!1});h.O.open&&h.O.open(h);f&&(c&=511,d="string"==typeof d?N(d,{pa:!0}).node:d,mb(d,{mode:c&4095|d.mode&-4096,V:Date.now(),fb:void 0}));!k.logReadFiles||b&1||a in db||(db[a]=1);return h}function sb(a,b,c){if(null===a.ia)throw new J(8);if(!a.seekable||!a.O.$)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.O.$(a,b,c);a.Ya=[]}
function R(a,b,c){a=Fa("/dev/"+a);var d=Ya(!!b,!!c);R.Ea??(R.Ea=64);var e=R.Ea++<<8|0;Qa(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,m){for(var n=0,v=0;v<m;v++){try{var x=b()}catch(r){throw new J(29);}if(void 0===x&&0===n)throw new J(6);if(null===x||void 0===x)break;n++;g[h+v]=x}n&&(f.node.ha=Date.now());return n},write(f,g,h,m){for(var n=0;n<m;n++)try{c(g[h+n])}catch(v){throw new J(29);}m&&(f.node.X=f.node.V=Date.now());return n}});pb(a,d,e)}
var S={},Ca=void 0,T=a=>{for(var b="";;){var c=y[a++];if(!c)return b;b+=String.fromCharCode(c)}},U={},V={},tb={},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},ub=a=>{throw new W(a);};function vb(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(V.hasOwnProperty(a)){if(c.Pa)return;throw new W(`Cannot register type '${d}' twice`);}V[a]=b;delete tb[a];U.hasOwnProperty(a)&&(b=U[a],delete U[a],b.forEach(e=>e()))}
function X(a,b,c={}){return vb(a,b,c)}
var wb=(a,b,c)=>{switch(b){case 1:return c?d=>q[d]:d=>y[d];case 2:return c?d=>z[d>>1]:d=>A[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>F[d>>3]:d=>ma[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},xb=[],Y=[0,1,,1,null,1,!0,1,!1,1],yb=a=>{9<a&&0===--Y[a+1]&&(Y[a]=void 0,xb.push(a))},zb=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Y[a]},Ab=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=
xb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}};function Db(a){return this.W(E[a>>2])}var Eb={name:"emscripten::val",W:a=>{var b=zb(a);yb(a);return b},ca:(a,b)=>Ab(b),ja:Db,Z:null},Fb=(a,b)=>{switch(b){case 4:return function(c){return this.W(ka[c>>2])};case 8:return function(c){return this.W(la[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Gb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Hb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Z)return!0;return!1}
var Ib=(a,b)=>{if(void 0===k[a].Y){var c=k[a];k[a]=function(...d){if(!k[a].Y.hasOwnProperty(d.length))throw new W(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${k[a].Y})!`);return k[a].Y[d.length].apply(this,d)};k[a].Y=[];k[a].Y[c.Aa]=c}},Jb=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].Y&&void 0!==k[a].Y[c])throw new W(`Cannot register public name '${a}' twice`);Ib(a,a);if(k[a].Y.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[a].Y[c]=b}else k[a]=b,k[a].Aa=c},Kb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>2]);return c},Lb=class extends Error{constructor(a){super(a);this.name="InternalError"}},Mb=[],Ob=a=>{var b=Mb[a];b||(Mb[a]=b=Nb.get(a));return b},Pb=(a,b)=>{a=T(a);var c=Ob(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};class Qb extends Error{}
var Sb=a=>{a=Rb(a);var b=T(a);Z(a);return b},Tb=(a,b)=>{function c(f){e[f]||V[f]||(tb[f]?tb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Qb(`${a}: `+d.map(Sb).join([", "]));},Ub=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Lb("Mismatched type converter count");for(var m=0;m<d.length;++m)X(d[m],h[m])}var d=[];d.forEach(h=>tb[h]=a);var e=Array(a.length),f=[],g=0;for(let [h,m]of a.entries())V.hasOwnProperty(m)?e[h]=V[m]:(f.push(m),U.hasOwnProperty(m)||(U[m]=
[]),U[m].push(()=>{e[h]=V[m];++g;g===f.length&&c(e)}));0===f.length&&c(e)},Vb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Wb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,Xb=(a,b,c)=>{a>>=1;b=La(A,a,b/2,c);if(16<b-a&&Wb)return Wb.decode(A.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(A[a]);return c},Yb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},
Zb=a=>2*a.length,$b=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},ac=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},bc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},cc=[],dc=a=>{var b=cc.length;cc.push(a);return b},ec=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=E[b+
4*d>>2],g=V[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Sb(f)}`,new W(a);c[e]=g}return c},fc=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>2]=Ab(d));return a},gc={},hc=a=>{var b=gc[a];return void 0===b?T(a):b},ic={},kc=()=>{if(!jc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in ic)void 0===ic[b]?delete a[b]:a[b]=ic[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
jc=c}return jc},jc;L=Array(4096);nb(K,"/");Q("/tmp");Q("/home");Q("/home/web_user");(function(){Q("/dev");Qa(259,{read:()=>0,write:(d,e,f,g)=>g,$:()=>0});pb("/dev/null",259);Pa(1280,Sa);Pa(1536,Ta);pb("/dev/tty",1280);pb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ia(a),b=a.byteLength);return a[--b]};R("random",c);R("urandom",c);Q("/dev/shm");Q("/dev/shm/tmp")})();
(function(){Q("/proc");var a=Q("/proc/self");Q("/proc/self/fd");nb({fa(){var b=Va(a,"fd",16895,73);b.O={$:K.O.$};b.R={la(c,d){c=+d;var e=P(c);c={parent:null,fa:{Ga:"fake"},R:{na:()=>e.path},id:c+1};return c.parent=c},za(){return Array.from(M.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k.print&&(fa=k.print);k.printErr&&(l=k.printErr);k.wasmBinary&&(p=k.wasmBinary);k.thisProgram&&(aa=k.thisProgram);
if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();
var Rb,lc,Z,mc,nc,oc,pa,Nb,rc={e:(a,b,c)=>{var d=new za(a);E[d.ta+16>>2]=0;E[d.ta+4>>2]=b;E[d.ta+8>>2]=c;Aa=a;Ba++;throw Aa;},m:function(a,b,c){Ca=c;try{var d=P(a);switch(b){case 0:var e=G();if(0>e)break;for(;M[e];)e++;return lb(d,e).ia;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=G(),d.flags|=e,0;case 12:return e=G(),z[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof S||"ErrnoError"!==f.name)throw f;return-f.da}},y:function(a,b,c){Ca=c;try{var d=P(a);
switch(b){case 21509:return d.T?0:-59;case 21505:if(!d.T)return-59;if(d.T.ga.Sa){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=G();D[e>>2]=25856;D[e+4>>2]=5;D[e+8>>2]=191;D[e+12>>2]=35387;for(var f=0;32>f;f++)q[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.T?0:-59;case 21506:case 21507:case 21508:if(!d.T)return-59;if(d.T.ga.Ta)for(e=G(),a=[],f=0;32>f;f++)a.push(q[e+f+17]);return 0;case 21519:if(!d.T)return-59;e=G();return D[e>>2]=0;case 21520:return d.T?
-28:-59;case 21537:case 21531:e=G();if(!d.O.Ra)throw new J(59);return d.O.Ra(d,b,e);case 21523:if(!d.T)return-59;d.T.ga.Ua&&(f=[24,80],e=G(),z[e>>1]=f[0],z[e+2>>1]=f[1]);return 0;case 21524:return d.T?0:-59;case 21515:return d.T?0:-59;default:return-28}}catch(g){if("undefined"==typeof S||"ErrnoError"!==g.name)throw g;return-g.da}},z:function(a,b,c,d){Ca=d;try{b=b?H(y,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":P(a).path;if(0==e.length)throw new J(44);b=f+"/"+e}var g=d?G():0;return rb(b,
c,g).ia}catch(h){if("undefined"==typeof S||"ErrnoError"!==h.name)throw h;return-h.da}},u:function(a,b){try{a=a?H(y,a):"";var c=N(a,{pa:!0}).node;var d=jb(c.R.ea)(c);E[b>>2]=d.Na;E[b+4>>2]=d.mode;E[b+8>>2]=d.Wa;E[b+12>>2]=d.uid;E[b+16>>2]=d.Oa;E[b+20>>2]=d.ma;F[b+24>>3]=BigInt(d.size);D[b+32>>2]=4096;D[b+36>>2]=d.Ma;var e=d.ha.getTime(),f=d.X.getTime(),g=d.V.getTime();F[b+40>>3]=BigInt(Math.floor(e/1E3));E[b+48>>2]=e%1E3*1E6;F[b+56>>3]=BigInt(Math.floor(f/1E3));E[b+64>>2]=f%1E3*1E6;F[b+72>>3]=BigInt(Math.floor(g/
1E3));E[b+80>>2]=g%1E3*1E6;F[b+88>>3]=BigInt(d.Qa);return 0}catch(h){if("undefined"==typeof S||"ErrnoError"!==h.name)throw h;return-h.da}},A:()=>qa(""),j:(a,b,c,d,e)=>{b=T(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}X(a,{name:b,W:f,ca:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},ja:wb(b,c,!d),Z:null})},o:(a,b,c,d)=>{b=T(b);X(a,{name:b,W:function(e){return!!e},ca:function(e,f){return f?c:d},ja:function(e){return this.W(y[e])},Z:null})},D:a=>X(a,Eb),n:(a,b,c)=>{b=
T(b);X(a,{name:b,W:d=>d,ca:(d,e)=>e,ja:Fb(b,c),Z:null})},d:(a,b,c,d,e,f,g)=>{var h=Kb(b,c);a=T(a);a=Vb(a);e=Pb(d,e);Jb(a,function(){Tb(`Cannot call ${a} due to unbound types`,h)},b-1);Ub(h,m=>{var n=a;var v=a;m=[m[0],null].concat(m.slice(1));var x=e,r=m.length;if(2>r)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=null!==m[1]&&!1,C=Hb(m),O=!m[0].Da,t=m[0],w=m[1];x=[v,ub,x,f,Gb,t.W.bind(t),w?.ca.bind(w)];for(t=2;t<r;++t)w=m[t],x.push(w.ca.bind(w));
if(!C)for(t=B?1:2;t<m.length;++t)null!==m[t].Z&&x.push(m[t].Z);C=Hb(m);t=m.length-2;var u=[];w=["fn"];B&&w.push("thisWired");for(r=0;r<t;++r)u.push(`arg${r}`),w.push(`arg${r}Wired`);u=u.join(",");w=w.join(",");u=`return function (${u}) {\n`;C&&(u+="var destructors = [];\n");var Bb=C?"destructors":"null",Ea="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");B&&(u+=`var thisWired = toClassParamWire(${Bb}, this);\n`);for(r=0;r<t;++r){var Cb=`toArg${r}Wire`;
u+=`var arg${r}Wired = ${Cb}(${Bb}, arg${r});\n`;Ea.push(Cb)}u+=(O||g?"var rv = ":"")+`invoker(${w});\n`;if(C)u+="runDestructors(destructors);\n";else for(r=B?1:2;r<m.length;++r)B=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==m[r].Z&&(u+=`${B}_dtor(${B});\n`,Ea.push(`${B}_dtor`));O&&(u+="var ret = fromRetWire(rv);\nreturn ret;\n");m=(new Function(Ea,u+"}\n"))(...x);v=Object.defineProperty(m,"name",{value:v});m=b-1;if(!k.hasOwnProperty(n))throw new Lb("Replacing nonexistent public symbol");void 0!==
k[n].Y&&void 0!==m?k[n].Y[m]=v:(k[n]=v,k[n].Aa=m);return[]})},b:(a,b,c,d,e)=>{b=T(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}X(a,{name:b,W:f,ca:(h,m)=>m,ja:wb(b,c,0!==d),Z:null})},a:(a,b,c)=>{function d(f){return new e(q.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=T(c);X(a,{name:c,W:d,ja:d},{Pa:!0})},E:(a,b)=>{b=T(b);X(a,{name:b,W(c){var d=(d=c+4)?H(y,d,E[c>>2],!0):"";
Z(c);return d},ca(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Na(d):d.length;var g=lc(4+f+1),h=g+4;E[g>>2]=f;e?I(d,h,f+1):y.set(d,h);null!==c&&c.push(Z,g);return g},ja:Db,Z(c){Z(c)}})},h:(a,b,c)=>{c=T(c);if(2===b){var d=Xb;var e=Yb;var f=Zb}else d=$b,e=ac,f=bc;X(a,{name:c,W:g=>{var h=d(g+4,E[g>>2]*b,!0);Z(g);return h},ca:(g,h)=>{if("string"!=typeof h)throw new W(`Cannot pass non-string to C++ string type ${c}`);
var m=f(h),n=lc(4+m+b);E[n>>2]=m/b;e(h,n+4,m+b);null!==g&&g.push(Z,n);return n},ja:Db,Z(g){Z(g)}})},p:(a,b)=>{b=T(b);X(a,{Da:!0,name:b,W:()=>{},ca:()=>{}})},s:()=>{throw Infinity;},i:(a,b,c)=>{var [d,...e]=ec(a,b);b=d.ca.bind(d);var f=e.map(m=>m.ja.bind(m));a--;var g={toValue:zb};a=f.map((m,n)=>{var v=`argFromPtr${n}`;g[v]=m;return`${v}(args${n?"+"+8*n:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=hc,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=
`(${a})`;d.Da||(g.toReturnWire=b,g.emval_returnValue=fc,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return dc(Object.defineProperty(c,"name",{value:h}))},g:(a,b,c,d,e)=>cc[a](b,c,d,e),c:a=>Ab(hc(a)),f:a=>{var b=zb(a);Gb(b);yb(a)},v:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();
e=(new Date(e,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(f,e);D[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(I(a,c,17),I(b,d,17)):(I(a,d,17),I(b,c,17))},t:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);
oa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},q:(a,b)=>{var c=0,d=0,e;for(e of kc()){var f=b+c;E[a+d>>2]=f;c+=I(e,f,Infinity)+1;d+=4}return 0},r:(a,b)=>{var c=kc();E[a>>2]=c.length;a=0;for(var d of c)a+=Na(d)+1;E[b>>2]=a;return 0},k:function(a){try{var b=P(a);if(null===b.ia)throw new J(8);b.xa&&(b.xa=null);try{b.O.close&&b.O.close(b)}catch(c){throw c;}finally{M[b.ia]=null}b.ia=null;return 0}catch(c){if("undefined"==typeof S||"ErrnoError"!==c.name)throw c;return c.da}},x:function(a,
b,c,d){try{a:{var e=P(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],m=E[a+4>>2];a+=8;var n=e,v=h,x=m,r=f,B=q;if(0>x||0>r)throw new J(28);if(null===n.ia)throw new J(8);if(1===(n.flags&2097155))throw new J(8);if(16384===(n.node.mode&61440))throw new J(31);if(!n.O.read)throw new J(28);var C="undefined"!=typeof r;if(!C)r=n.position;else if(!n.seekable)throw new J(70);var O=n.O.read(n,B,v,x,r);C||(n.position+=O);var t=O;if(0>t){var w=-1;break a}b+=t;if(t<m)break;"undefined"!=typeof f&&(f+=t)}w=b}E[d>>
2]=w;return 0}catch(u){if("undefined"==typeof S||"ErrnoError"!==u.name)throw u;return u.da}},w:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=P(a);sb(e,b,c);F[d>>3]=BigInt(e.position);e.xa&&0===b&&0===c&&(e.xa=null);return 0}catch(f){if("undefined"==typeof S||"ErrnoError"!==f.name)throw f;return f.da}},l:function(a,b,c,d){try{a:{var e=P(a);a=b;for(var f,g=b=0;g<c;g++){var h=E[a>>2],m=E[a+4>>2];a+=8;var n=e,v=h,x=m,r=f,B=q;if(0>x||0>r)throw new J(28);
if(null===n.ia)throw new J(8);if(0===(n.flags&2097155))throw new J(8);if(16384===(n.node.mode&61440))throw new J(31);if(!n.O.write)throw new J(28);n.seekable&&n.flags&1024&&sb(n,0,2);var C="undefined"!=typeof r;if(!C)r=n.position;else if(!n.seekable)throw new J(70);var O=n.O.write(n,B,v,x,r,void 0);C||(n.position+=O);var t=O;if(0>t){var w=-1;break a}b+=t;if(t<m)break;"undefined"!=typeof f&&(f+=t)}w=b}E[d>>2]=w;return 0}catch(u){if("undefined"==typeof S||"ErrnoError"!==u.name)throw u;return u.da}},
C:pc,B:qc};function pc(a,b,c){var d=oc();try{return Ob(a)(b,c)}catch(e){nc(d);if(e!==e+0)throw e;mc(1,0)}}function qc(a,b,c){var d=oc();try{Ob(a)(b,c)}catch(e){nc(d);if(e!==e+0)throw e;mc(1,0)}}var sc;
sc=await (async function(){function a(c){c=sc=c.exports;Rb=c.H;lc=c.J;Z=c.K;k._main=c.L;mc=c.M;nc=c.N;oc=c.P;pa=c.F;Nb=c.I;oa();return sc}var b={a:rc};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ra??=k.locateFile?k.locateFile?k.locateFile("jxl.wasm",ca):ca+"jxl.wasm":(new URL("jxl.wasm",import.meta.url)).href;return a((await ua(b)).instance)}());
(function(){function a(){k.calledRun=!0;if(!ha){na=!0;if(!k.noFSInit&&!bb){var b,c;bb=!0;b??=k.stdin;c??=k.stdout;d??=k.stderr;b?R("stdin",b):qb("/dev/tty","/dev/stdin");c?R("stdout",null,c):qb("/dev/tty","/dev/stdout");d?R("stderr",null,d):qb("/dev/tty1","/dev/stderr");rb("/dev/stdin",0);rb("/dev/stdout",1);rb("/dev/stderr",1)}sc.G();cb=!1;ia?.(k);k.onRuntimeInitialized?.();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var d=k.postRun.shift();wa.push(d)}va(wa)}}
if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)ya();va(xa);k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);a()},1)):a()})();na?moduleRtn=k:moduleRtn=new Promise((a,b)=>{ia=a;ja=b});
;return moduleRtn}export default createJxlModule;
