async function createJxlModule(moduleArg={}){var Module=moduleArg;var aa="./this.program",ba=import.meta.url,ca="",da,ea;try{ca=(new URL(".",ba)).href}catch{}ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),h=console.error.bind(console),ha=!1;class ia{}class ja extends ia{}function ka(){if(!m?.buffer?.resizable){var a=la.buffer;
m=new Int8Array(a);n=new Int16Array(a);x=new Uint8Array(a);y=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);ma=new Float32Array(a);oa=new Float64Array(a);B=new BigInt64Array(a);pa=new BigUint64Array(a)}}function qa(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),ra.push(...a));for(a=ra;a.length>0;)a.shift()(Module)}function sa(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),ta.push(...a));for(a=ta;a.length>0;)a.shift()(Module)}function ua(a){Module.onAbort?.(a);a=`Aborted(${a})`;
h(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;async function wa(a){try{var b=await da(a);return new Uint8Array(b)}catch{}if(ea)a=ea(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function ya(a){var b=va;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,
a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return xa(b,a)}var m,ta=[],ra=[],Aa=a=>za(a),Ca=()=>Ba(),A;class Da{constructor(a){this.ua=a-24}init(a,b){A[this.ua+16>>2]=0;A[this.ua+4>>2]=a;A[this.ua+8>>2]=b}}var Ea=0,z,G=()=>{var a=z[+E>>2];E+=4;return a},Fa=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ga=a=>{var b=a.charAt(0)===
"/",c=a.slice(-1)==="/";(a=Fa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ha=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ia=()=>a=>(crypto.getRandomValues(a),0),Ja=a=>(Ja=Ia())(a),Ka=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";
b=c+"/"+b;c=c.charAt(0)==="/"}b=Fa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},La=globalThis.TextDecoder&&new TextDecoder,Ma=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},H=(a,b=0,c,d)=>{c=Ma(a,b,c,d);if(c-b>16&&a.buffer&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?
d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Na=[],Oa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},I=(a,b,c)=>{var d=x;if(!(c>0))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(b>=c)break;d[b++]=g}else if(g<=2047){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(g<=65535){if(b+2>=c)break;
d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Pa=[];function Qa(a,b){Pa[a]={input:[],output:[],ja:b};Ra(a,Sa)}var Sa={open(a){var b=Pa[a.node.oa];if(!b)throw new J(43);a.V=b;a.seekable=!1},close(a){a.V.ja.ra(a.V)},ra(a){a.V.ja.ra(a.V)},read(a,b,c,d){if(!a.V||!a.V.ja.Da)throw new J(60);for(var e=0,f=0;f<d;f++){try{var g=a.V.ja.Da(a.V)}catch(k){throw new J(29);}if(g===void 0&&!e)throw new J(6);
if(g===null||g===void 0)break;e++;b[c+f]=g;if(g===10)break}e&&(a.node.ha=Date.now());return e},write(a,b,c,d){if(!a.V||!a.V.ja.za)throw new J(60);try{for(var e=0;e<d;e++)a.V.ja.za(a.V,b[c+e])}catch(f){throw new J(29);}d&&(a.node.Z=a.node.X=Date.now());return e}},Ta={Da(){return Na.length?Na.shift():null},za(a,b){b===null||b===10?(fa(H(a.output)),a.output=[]):b!=0&&a.output.push(b)},ra(a){a.output?.length>0&&(fa(H(a.output)),a.output=[])},Wa(){return{kb:25856,mb:5,jb:191,lb:35387,ib:[3,28,127,21,4,
0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Xa(){return 0},Ya(){return[24,80]}},Ua={za(a,b){b===null||b===10?(h(H(a.output)),a.output=[]):b!=0&&a.output.push(b)},ra(a){a.output?.length>0&&(h(H(a.output)),a.output=[])}},K={fa:null,ia(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new J(63);K.fa||(K.fa={dir:{node:{ba:K.S.ba,ka:K.S.ka,na:K.S.na,sa:K.S.sa,Ja:K.S.Ja,La:K.S.La,Ka:K.S.Ka,Aa:K.S.Aa,va:K.S.va},stream:{ea:K.U.ea}},
file:{node:{ba:K.S.ba,ka:K.S.ka},stream:{ea:K.U.ea,read:K.U.read,write:K.U.write,Ga:K.U.Ga,Ia:K.U.Ia}},link:{node:{ba:K.S.ba,ka:K.S.ka,pa:K.S.pa},stream:{}},Ca:{node:{ba:K.S.ba,ka:K.S.ka},stream:Va}});c=Wa(a,b,c,d);(c.mode&61440)===16384?(c.S=K.fa.dir.node,c.U=K.fa.dir.stream,c.W={}):(c.mode&61440)===32768?(c.S=K.fa.file.node,c.U=K.fa.file.stream,c.$=0,c.W=K.Ra??(K.Ra=new Uint8Array(0))):(c.mode&61440)===40960?(c.S=K.fa.link.node,c.U=K.fa.link.stream):(c.mode&61440)===8192&&(c.S=K.fa.Ca.node,c.U=
K.fa.Ca.stream);c.ha=c.Z=c.X=Date.now();a&&(a.W[b]=c,a.ha=a.Z=a.X=c.ha);return c},S:{ba(a){var b={};b.Qa=(a.mode&61440)===8192?a.id:1;b.Ua=a.id;b.mode=a.mode;b.bb=1;b.uid=0;b.Sa=0;b.oa=a.oa;(a.mode&61440)===16384?b.size=4096:(a.mode&61440)===32768?b.size=a.$:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.ha=new Date(a.ha);b.Z=new Date(a.Z);b.X=new Date(a.X);b.Ma=a.ha;b.$a=a.Z;b.Pa=a.X;b.Na=4096;b.Oa=Math.ceil(b.size/b.Na);return b},ka(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=
null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.$!=b&&(c=a.W,a.W=new Uint8Array(b),a.W.set(c.subarray(0,Math.min(b,a.$))),a.$=b))},na(){K.wa||(K.wa=new J(44),K.wa.stack="<generic error, no stack>");throw K.wa;},sa(a,b,c,d){return K.createNode(a,b,c,d)},Ja(a,b,c){try{var d=Xa(b,c)}catch(f){}if(d&&(a.mode&61440)===16384)for(var e in d.W)throw new J(55);delete a.parent.W[a.name];b.W[c]=a;a.name=c;b.X=b.Z=a.parent.X=a.parent.Z=Date.now()},La(a,b){delete a.W[b];a.X=a.Z=Date.now()},Ka(a,b){var c=Xa(a,b),
d;for(d in c.W)throw new J(55);delete a.W[b];a.X=a.Z=Date.now()},Aa(a){return[".","..",...Object.keys(a.W)]},va(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},pa(a){if((a.mode&61440)!==40960)throw new J(28);return a.link}},U:{read(a,b,c,d,e){if(e>=a.node.$)return 0;d=Math.min(a.node.$-e,d);b.set(a.node.W.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.Z=a.X=Date.now();if(f)a.W=b.subarray(c,c+d),a.$=d;else if(a.$||e){f=e+d;var g=a.W.length;
g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.W.subarray(0,a.$),a.W=new Uint8Array(f),a.W.set(g));a.W.set(b.subarray(c,c+d),e);a.$=Math.max(a.$,e+d)}else a.W=b.slice(c,c+d),a.$=d;return d},ea(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.$);if(b<0)throw new J(28);return b},Ga(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new J(43);a=a.node.W;if(e&2||a.buffer!==m.buffer){d=!0;ua();e=void 0;if(!e)throw new J(48);if(a){if(c>0||c+b<a.length)a.subarray?
a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{ua:e,gb:d}},Ia(a,b,c,d){K.U.write(a,b,0,d,c,!1);return 0}}},Ya=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Za=null,$a={},L=[],ab=1,bb=[],cb=!1,db=!0,J=class{name="ErrnoError";constructor(a){this.aa=a}},eb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},fb=class{S=
{};U={};ta=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ia=a.ia;this.id=ab++;this.name=b;this.mode=c;this.oa=d;this.ha=this.Z=this.X=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}eb(){}};function M(a,b={}){if(!a)throw new J(44);b.xa??(b.xa=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(k=>!!k);for(var d=Za,e="/",f=0;f<a.length;f++){var g=
f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Ha(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ga(e+"/"+a[f]);try{d=Xa(d,a[f])}catch(k){if(k?.aa===44&&g&&b.cb)return{path:e};throw k;}!d.ta||g&&!b.xa||(d=d.ta.root);if((d.mode&61440)===40960&&(!g||b.qa)){if(!d.S.pa)throw new J(52);d=d.S.pa(d);d.charAt(0)==="/"||(d=Ha(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new J(32);}function gb(a,b){for(var c=
0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%bb.length}function Xa(a,b){var c=(a.mode&61440)===16384?(c=hb(a,"x"))?c:a.S.na?0:2:54;if(c)throw new J(c);for(c=bb[gb(a.id,b)];c;c=c.ab){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.S.na(a,b)}function Wa(a,b,c,d){a=new fb(a,b,c,d);b=gb(a.parent.id,a.name);a.ab=bb[b];return bb[b]=a}function hb(a,b){return db?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function ib(a,
b){if((a.mode&61440)!==16384)return 54;try{return Xa(a,b),20}catch(c){}return hb(a,"wx")}function jb(a){if(!a)throw new J(63);return a}function N(a){a=L[a];if(!a)throw new J(8);return a}function kb(a,b=-1){a=Object.assign(new eb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!L[b])break a;throw new J(33);}a.la=b;return L[b]=a}function lb(a,b=-1){a=kb(a,b);a.U?.ob?.(a);return a}function mb(a,b){var c=void 0,d=c?null:a;c??=a.S.ka;jb(c);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new J(22);throw e;}}
var Va={open(a){a.U=$a[a.node.oa].U;a.U.open?.(a)},ea(){throw new J(70);}};function Ra(a,b){$a[a]={U:b}}function nb(a,b){var c=b==="/";if(c&&Za)throw new J(10);if(!c&&b){var d=M(b,{xa:!1});b=d.path;d=d.node;if(d.ta)throw new J(10);if((d.mode&61440)!==16384)throw new J(54);}b={type:a,pb:{},Ha:b,Za:[]};a=a.ia(b);a.ia=b;b.root=a;c?Za=a:d&&(d.ta=b,d.ia&&d.ia.Za.push(b))}function ob(a,b,c){var d=M(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new J(28);if(a==="."||a==="..")throw new J(20);
var e=ib(d,a);if(e)throw new J(e);if(!d.S.sa)throw new J(63);return d.S.sa(d,a,b,c)}function P(a){return ob(a,16895,0)}function pb(a,b,c){typeof c=="undefined"&&(c=b,b=438);ob(a,b|8192,c)}function qb(a,b){if(!Ka(a))throw new J(44);var c=M(b,{parent:!0}).node;if(!c)throw new J(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=ib(c,b);if(d)throw new J(d);if(!c.S.va)throw new J(63);c.S.va(c,b,a)}function rb(a,b=!1){a=M(a,{qa:!b}).node;return jb(a.S.ba)(a)}function sb(a,b,c=438){if(a==="")throw new J(44);
if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=M(a,{qa:!(b&131072),cb:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new J(20);}else{if(e)throw new J(31);d=ob(a,c|511,0);f=!0}if(!d)throw new J(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&(d.mode&61440)!==16384)throw new J(54);if(!f&&(d?(d.mode&61440)===
40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=(d.mode&61440)===16384&&(e!=="r"||b&576)?31:hb(d,e)):e=44,e))throw new J(e);if(b&512&&!f){e=d;e=typeof e=="string"?M(e,{qa:!0}).node:e;if((e.mode&61440)===16384)throw new J(31);if((e.mode&61440)!==32768)throw new J(28);if(a=hb(e,"w"))throw new J(a);mb(e,{size:0,timestamp:Date.now()})}a:{for(e=d;;){if(e===e.parent){e=e.ia.Ha;var g=g?e[e.length-1]!=="/"?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}g=void 0}b=kb({node:d,path:g,flags:b&
-131713,seekable:!0,position:0,U:d.U,fb:[],error:!1});b.U.open&&b.U.open(b);f&&(c&=511,d=typeof d=="string"?M(d,{qa:!0}).node:d,mb(d,{mode:c&4095|d.mode&-4096,X:Date.now(),nb:!1}));return b}function tb(a,b,c){if(a.la===null)throw new J(8);if(!a.seekable||!a.U.ea)throw new J(70);if(c!=0&&c!=1&&c!=2)throw new J(28);a.position=a.U.ea(a,b,c);a.fb=[]}function ub(a,b,c,d){var e=void 0;if(d<0||e<0)throw new J(28);if(a.la===null)throw new J(8);if((a.flags&2097155)===0)throw new J(8);if((a.node.mode&61440)===
16384)throw new J(31);if(!a.U.write)throw new J(28);a.seekable&&a.flags&1024&&tb(a,0,2);var f=typeof e!="undefined";if(!f)e=a.position;else if(!a.seekable)throw new J(70);b=a.U.write(a,b,c,d,e,void 0);f||(a.position+=b);return b}function vb(){var a,b,c;cb=!0;a??=Module.stdin;b??=Module.stdout;c??=Module.stderr;a?Q("stdin",a):qb("/dev/tty","/dev/stdin");b?Q("stdout",null,b):qb("/dev/tty","/dev/stdout");c?Q("stderr",null,c):qb("/dev/tty1","/dev/stderr");sb("/dev/stdin",0);sb("/dev/stdout",1);sb("/dev/stderr",
1)}function Q(a,b,c){a=Ga("/dev/"+a);var d=Ya(!!b,!!c);Q.Fa??(Q.Fa=64);var e=Q.Fa++<<8|0;Ra(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,l){for(var p=0,r=0;r<l;r++){try{var t=b()}catch(w){throw new J(29);}if(t===void 0&&!p)throw new J(6);if(t===null||t===void 0)break;p++;g[k+r]=t}p&&(f.node.ha=Date.now());return p},write(f,g,k,l){for(var p=0;p<l;p++)try{c(g[k+p])}catch(r){throw new J(29);}l&&(f.node.Z=f.node.X=Date.now());return p}});pb(a,d,e)}var R={},x,B;function wb(a,
b,c=!1){if(b.charAt(0)==="/")return b;a=a===-100?"/":N(a).path;if(b.length==0){if(!c)throw new J(44);return a}return a+"/"+b}function xb(a,b){A[a>>2]=b.Qa;A[a+4>>2]=b.mode;A[a+8>>2]=b.bb;A[a+12>>2]=b.uid;A[a+16>>2]=b.Sa;A[a+20>>2]=b.oa;B[a+24>>3]=BigInt(b.size);z[a+32>>2]=4096;z[a+36>>2]=b.Oa;var c=b.Ma??b.ha.getTime(),d=b.$a??b.Z.getTime(),e=b.Pa??b.X.getTime();B[a+40>>3]=BigInt(Math.floor(c/1E3));A[a+48>>2]=Math.floor(c%1E3*1E6);B[a+56>>3]=BigInt(Math.floor(d/1E3));A[a+64>>2]=Math.floor(d%1E3*1E6);
B[a+72>>3]=BigInt(Math.floor(e/1E3));A[a+80>>2]=Math.floor(e%1E3*1E6);B[a+88>>3]=BigInt(b.Ua);return 0}var E=void 0,n,S=a=>{for(var b="";;){var c=x[a++];if(!c)return b;b+=String.fromCharCode(c)}},T={},U={},yb={};class V extends Error{constructor(a){super(a);this.name="BindingError"}}var zb=a=>{throw new V(a);};function Cb(a,b,c={}){var d=b.name;if(!a)throw new V(`type "${d}" must have a positive integer typeid pointer`);if(U.hasOwnProperty(a)){if(c.Ta)return;throw new V(`Cannot register type '${d}' twice`);
}U[a]=b;delete yb[a];T.hasOwnProperty(a)&&(b=T[a],delete T[a],b.forEach(e=>e()))}function W(a,b,c={}){return Cb(a,b,c)}var y,pa,Db=(a,b,c)=>{switch(b){case 1:return c?d=>m[d]:d=>x[d];case 2:return c?d=>n[d>>1]:d=>y[d>>1];case 4:return c?d=>z[d>>2]:d=>A[d>>2];case 8:return c?d=>B[d>>3]:d=>pa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Eb=[],X=[0,1,,1,null,1,!0,1,!1,1],Fb=a=>{a>9&&0===--X[a+1]&&(X[a]=void 0,Eb.push(a))},Gb=a=>{if(!a)throw new V(`Cannot use deleted val. handle = ${a}`);
return X[a]},Hb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=Eb.pop()||X.length;X[b]=a;X[b+1]=1;return b}};function Ib(a){return this.Y(A[a>>2])}var Jb={name:"emscripten::val",Y:a=>{var b=Gb(a);Fb(a);return b},ga:(a,b)=>Hb(b),ma:Ib,da:null},ma,oa,Kb=(a,b)=>{switch(b){case 4:return function(c){return this.Y(ma[c>>2])};case 8:return function(c){return this.Y(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Lb=a=>{for(;a.length;){var b=
a.pop();a.pop()(b)}};function Mb(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].da===void 0)return!0;return!1}function Nb(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].hb)return!0;return!1}var Ob=(a,b)=>{var c=Module;if(void 0===c[a].ca){var d=c[a];c[a]=function(...e){if(!c[a].ca.hasOwnProperty(e.length))throw new V(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].ca})!`);return c[a].ca[e.length].apply(this,e)};c[a].ca=[];c[a].ca[d.Ba]=d}},
Pb=(a,b,c)=>{if(Module.hasOwnProperty(a)){if(void 0===c||void 0!==Module[a].ca&&void 0!==Module[a].ca[c])throw new V(`Cannot register public name '${a}' twice`);Ob(a,a);if(Module[a].ca.hasOwnProperty(c))throw new V(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);Module[a].ca[c]=b}else Module[a]=b,Module[a].Ba=c},Qb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(A[b+d*4>>2]);return c};class Rb extends Error{constructor(a){super(a);this.name="InternalError"}}var Sb=
[],Ub=a=>{var b=Sb[a];b||(Sb[a]=b=Tb.get(a));return b},Vb=(a,b)=>{a=S(a);var c=Ub(b);if(typeof c!="function")throw new V(`unknown function pointer with signature ${a}: ${b}`);return c};class Wb extends Error{}var Yb=a=>{a=Xb(a);var b=S(a);Y(a);return b},Zb=(a,b)=>{function c(f){e[f]||U[f]||(yb[f]?yb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Wb(`${a}: `+d.map(Yb).join([", "]));},$b=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Rb("Mismatched type converter count");
for(var l=0;l<d.length;++l)W(d[l],k[l])}var d=[];d.forEach(k=>yb[k]=a);var e=Array(a.length),f=[],g=0;for(let [k,l]of a.entries())U.hasOwnProperty(l)?e[k]=U[l]:(f.push(l),T.hasOwnProperty(l)||(T[l]=[]),T[l].push(()=>{e[k]=U[l];++g;g===f.length&&c(e)}));0===f.length&&c(e)},ac=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},bc=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,cc=(a,b,c)=>{a>>=1;b=Ma(y,a,b/2,c);if(b-a>16&&bc)return bc.decode(y.subarray(a,b));for(c="";a<b;++a)c+=
String.fromCharCode(y[a]);return c},dc=(a,b,c=2147483647)=>{if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)n[b>>1]=a.charCodeAt(e),b+=2;n[b>>1]=0;return b-d},ec=a=>a.length*2,fc=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=A[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},hc=(a,b,c=2147483647)=>{if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;z[b>>2]=f;b+=4;if(b+4>c)break}z[b>>2]=0;return b-d},ic=
a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},jc=[],kc=a=>{var b=jc.length;jc.push(a);return b},lc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=A[b+d*4>>2],g=U[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Yb(f)}`,new V(a);c[e]=g}return c},mc=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(A[b>>2]=Hb(d));return a},nc={},oc=a=>{var b=nc[a];return b===void 0?S(a):b},pc={},rc=()=>{if(!qc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:aa},b;for(b in pc)pc[b]===void 0?delete a[b]:a[b]=pc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qc=c}return qc},qc;bb.length=4096;nb(K,"/");P("/tmp");P("/home");P("/home/web_user");(function(){P("/dev");Ra(259,{read:()=>0,write:(d,e,f,g)=>g,ea:()=>0});pb("/dev/null",259);Qa(1280,Ta);Qa(1536,Ua);pb("/dev/tty",1280);pb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b||(Ja(a),b=a.byteLength);return a[--b]};Q("random",
c);Q("urandom",c);P("/dev/shm");P("/dev/shm/tmp")})();(function(){P("/proc");var a=P("/proc/self");P("/proc/self/fd");nb({ia(){var b=Wa(a,"fd",16895,73);b.U={ea:K.U.ea};b.S={na(c,d){c=+d;var e=N(c);c={parent:null,ia:{Ha:"fake"},S:{pa:()=>e.path},id:c+1};return c.parent=c},Aa(){return Array.from(L.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();Module.print&&(fa=Module.print);Module.printErr&&(h=Module.printErr);Module.thisProgram&&(aa=Module.thisProgram);var Z=
Module.preInit;if(Z)for(typeof Z=="function"&&(Module.preInit=Z=[Z]);Z.length>0;)Z.shift()();var Xb,sc,Y,tc,za,Ba,la,Tb,wc={i:(a,b,c)=>{(new Da(a)).init(b,c);Ea++;ua()},o:function(a,b,c){E=c;try{var d=N(a);switch(b){case 0:var e=G();if(e<0)break;for(;L[e];)e++;return lb(d,e).la;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=G(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=G(),n[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof R=="undefined"||f.name!=="ErrnoError")throw f;
return-f.aa}},A:function(a,b){try{var c=N(a),d=c.node,e=c.U.ba;a=e?c:d;e??=d.S.ba;jb(e);var f=e(a);return xb(b,f)}catch(g){if(typeof R=="undefined"||g.name!=="ErrnoError")throw g;return-g.aa}},C:function(a,b,c){E=c;try{var d=N(a);switch(b){case 21509:return d.V?0:-59;case 21505:if(!d.V)return-59;if(d.V.ja.Wa){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=G();z[e>>2]=25856;z[e+4>>2]=5;z[e+8>>2]=191;z[e+12>>2]=35387;for(var f=0;f<32;f++)m[e+f+17]=a[f]||0}return 0;
case 21510:case 21511:case 21512:return d.V?0:-59;case 21506:case 21507:case 21508:if(!d.V)return-59;if(d.V.ja.Xa)for(e=G(),a=[],f=0;f<32;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.V)return-59;e=G();return z[e>>2]=0;case 21520:return d.V?-28:-59;case 21537:case 21531:e=G();if(!d.U.Va)throw new J(59);return d.U.Va(d,b,e);case 21523:if(!d.V)return-59;d.V.ja.Ya&&(f=[24,80],e=G(),n[e>>1]=f[0],n[e+2>>1]=f[1]);return 0;case 21524:return d.V?0:-59;case 21515:return d.V?0:-59;default:return-28}}catch(g){if(typeof R==
"undefined"||g.name!=="ErrnoError")throw g;return-g.aa}},z:function(a,b,c,d){try{b=b?H(x,b):"";var e=d&256;b=wb(a,b,d&4096);return xb(c,e?rb(b,!0):rb(b))}catch(f){if(typeof R=="undefined"||f.name!=="ErrnoError")throw f;return-f.aa}},D:function(a,b,c,d){E=d;try{b=b?H(x,b):"";b=wb(a,b);var e=d?G():0;c&64&&(e&=-19);return sb(b,c,e).la}catch(f){if(typeof R=="undefined"||f.name!=="ErrnoError")throw f;return-f.aa}},E:()=>ua(""),r:(a,b,c,d,e)=>{b=S(b);d=d===0n;var f=g=>g;if(d){let g=c*8;f=k=>BigInt.asUintN(g,
k);e=f(e)}W(a,{name:b,Y:f,ga:(g,k)=>{typeof k=="number"&&(k=BigInt(k));return k},ma:Db(b,c,!d),da:null})},I:(a,b,c,d)=>{b=S(b);W(a,{name:b,Y:function(e){return!!e},ga:function(e,f){return f?c:d},ma:function(e){return this.Y(x[e])},da:null})},G:a=>W(a,Jb),q:(a,b,c)=>{b=S(b);W(a,{name:b,Y:d=>d,ga:(d,e)=>e,ma:Kb(b,c),da:null})},h:(a,b,c,d,e,f,g)=>{var k=Qb(b,c);a=S(a);a=ac(a);e=Vb(d,e);Pb(a,function(){Zb(`Cannot call ${a} due to unbound types`,k)},b-1);$b(k,l=>{var p=a;var r=a;l=[l[0],null].concat(l.slice(1));
var t=e,w=l.length;if(w<2)throw new V("argTypes array size mismatch! Must at least get return value and receiver (this) types!");var F=l[1]!==null&&!1,C=Mb(l),O=Nb(l),q=O&&!g&&!C;O&&!q&&(C=!0);O=!l[0].Ea;var D=l[0],u=l[1];t=[r,zb,t,f,Lb,D.Y.bind(D),u?.ga.bind(u)];q&&t.push(Ca,Aa);for(q=2;q<w;++q)D=l[q],t.push(D.ga.bind(D));if(!C)for(q=F?1:2;q<l.length;++q)l[q].da!==null&&t.push(l[q].da);w=Mb(l);C=(q=Nb(l))&&!g&&!w;q&&!C&&(w=!0);D=l.length-2;var v=[];u=["fn"];F&&u.push("thisWired");for(q=0;q<D;++q)v.push(`arg${q}`),
u.push(`arg${q}Wired`);v=v.join();u=u.join();v=`return function (${v}) {\n`;w&&(v+="var destructors = [];\n");C&&(v+="var sp = stackSave();\ntry {\n");var Ab=w?"destructors":"null",na="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");C&&na.push("stackSave","stackRestore");F&&(v+=`var thisWired = toClassParamWire(${Ab}, this);\n`);for(q=0;q<D;++q){var Bb=`toArg${q}Wire`;v+=`var arg${q}Wired = ${Bb}(${Ab}, arg${q});\n`;na.push(Bb)}v+=(O||g?"var rv = ":"")+
`invoker(${u});\n`;C&&(v+="} finally {\nstackRestore(sp);\n}\n");if(w)v+="runDestructors(destructors);\n";else for(q=F?1:2;q<l.length;++q)F=q===1?"thisWired":`arg${q-2}Wired`,l[q].da!==null&&(v+=`${F}_dtor(${F});\n`,na.push(`${F}_dtor`));O&&(v+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(na,v+"}\n"))(...t);r=Object.defineProperty(l,"name",{value:r});l=b-1;if(!Module.hasOwnProperty(p))throw new Rb("Replacing nonexistent public symbol");void 0!==Module[p].ca&&void 0!==l?Module[p].ca[l]=
r:(Module[p]=r,Module[p].Ba=l);return[]})},b:(a,b,c,d,e)=>{b=S(b);var f=k=>k;if(d===0){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}W(a,{name:b,Y:f,ga:(k,l)=>l,ma:Db(b,c,d!==0),da:null})},a:(a,b,c)=>{function d(f){return new e(m.buffer,A[f+4>>2],A[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=S(c);W(a,{name:c,Y:d,ma:d},{Ta:!0})},H:(a,b)=>{b=S(b);W(a,{name:b,Y(c){var d=(d=c+4)?H(x,d,A[c>>2],!0):"";Y(c);return d},ga(c,
d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e=typeof d=="string";if(!(e||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new V("Cannot pass non-string to std::string");var f=e?Oa(d):d.length;var g=sc(4+f+1),k=g+4;A[g>>2]=f;e?I(d,k,f+1):x.set(d,k);c!==null&&c.push(Y,g);return g},ma:Ib,da(c){Y(c)}})},j:(a,b,c)=>{c=S(c);if(b===2){var d=cc;var e=dc;var f=ec}else d=fc,e=hc,f=ic;W(a,{name:c,Y:g=>{var k=d(g+4,A[g>>2]*b,!0);Y(g);return k},ga:(g,k)=>{if(typeof k!="string")throw new V(`Cannot pass non-string to C++ string type ${c}`);
var l=f(k),p=sc(4+l+b);A[p>>2]=l/b;e(k,p+4,l+b);g!==null&&g.push(Y,p);return p},ma:Ib,da(g){Y(g)}})},s:(a,b)=>{b=S(b);W(a,{Ea:!0,name:b,Y:()=>{},ga:()=>{}})},v:()=>{throw new ja;},f:(a,b,c)=>{var d;[b,...d]=lc(a,b);var e=b.ga.bind(b),f=d.map(l=>l.ma.bind(l));a--;var g={toValue:Gb};a=f.map((l,p)=>{var r=`argFromPtr${p}`;g[r]=l;return`${r}(args${p?"+"+p*8:""})`});switch(c){case 0:var k="toValue(handle)";break;case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:g.getStringOrSymbol=oc,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=
`(${a})`;b.Ea||(g.toReturnWire=e,g.emval_returnValue=mc,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(g),k))(...Object.values(g));b=`methodCaller<(${d.map(l=>l.name)}) => ${b.name}>`;return kc(Object.defineProperty(c,"name",{value:b}))},g:Fb,l:(a,b)=>{a=Gb(a);b=Gb(b);return Hb(a[b])},k:a=>{a>9&&(X[a+1]+=1)},e:(a,b,c,d,e)=>jc[a](b,c,d,e),c:a=>Hb(oc(a)),d:a=>{var b=Gb(a);Lb(b);Fb(a)},
x:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();A[a>>2]=Math.max(f,e)*60;z[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(I(a,c,17),I(b,d,17)):(I(a,d,17),I(b,c,17))},w:a=>{var b=x.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
Math.ceil(Math.max(a,d)/65536)*65536)-la.buffer.byteLength+65535)/65536|0;try{la.grow(d);ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:(a,b)=>{var c=0,d=0,e;for(e of rc()){var f=b+c;A[a+d>>2]=f;c+=I(e,f,Infinity)+1;d+=4}return 0},u:(a,b)=>{var c=rc();A[a>>2]=c.length;a=0;for(var d of c)a+=Oa(d)+1;A[b>>2]=a;return 0},m:function(a){try{var b=N(a);if(b.la===null)throw new J(8);b.ya&&(b.ya=null);b.node?.eb();try{b.U.close&&b.U.close(b)}catch(c){throw c;}finally{L[b.la]=null}b.la=null;
return 0}catch(c){if(typeof R=="undefined"||c.name!=="ErrnoError")throw c;return c.aa}},B:function(a,b,c,d){try{a:{var e=N(a);a=b;for(var f,g=b=0;g<c;g++){var k=A[a>>2],l=A[a+4>>2];a+=8;try{var p=e,r=k,t=l,w=f,F=m;if(t<0||w<0)throw new J(28);if(p.la===null)throw new J(8);if((p.flags&2097155)===1)throw new J(8);if((p.node.mode&61440)===16384)throw new J(31);if(!p.U.read)throw new J(28);var C=typeof w!="undefined";if(!C)w=p.position;else if(!p.seekable)throw new J(70);var O=p.U.read(p,F,r,t,w);C||(p.position+=
O);var q=O}catch(u){if(b>0&&u instanceof J&&(u.aa==6||u.aa==6))break;throw u;}if(q<0){var D=-1;break a}b+=q;if(q<l)break;typeof f!="undefined"&&(f+=q)}D=b}A[d>>2]=D;return 0}catch(u){if(typeof R=="undefined"||u.name!=="ErrnoError")throw u;return u.aa}},y:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=N(a);tb(e,b,c);B[d>>3]=BigInt(e.position);e.ya&&!b&&c===0&&(e.ya=null);return 0}catch(f){if(typeof R=="undefined"||f.name!=="ErrnoError")throw f;
return f.aa}},n:function(a,b,c,d){try{var e=N(a);a=b;if(c==1)var f=ub(e,m,A[a>>2],A[a+4>>2]);else{for(var g=b=0,k=a;g<c;g++,k+=8)b+=A[k+4>>2];var l=new Uint8Array(b);for(g=k=0;g<c;g++,a+=8){var p=A[a>>2],r=A[a+4>>2];l.set(x.subarray(p,p+r),k);k+=r}f=ub(e,l,0,b)}A[d>>2]=f;return 0}catch(t){if(typeof R=="undefined"||t.name!=="ErrnoError")throw t;return t.aa}},p:uc,F:vc};function uc(a,b,c){var d=Ba();try{return Ub(a)(b,c)}catch(e){za(d);if(!(e instanceof ia))throw e;tc(1,0)}}function vc(a,b,c){var d=
Ba();try{Ub(a)(b,c)}catch(e){za(d);if(!(e instanceof ia))throw e;tc(1,0)}}var xc;xc=await (async function(){function a(d){d=xc=d.exports;Xb=d.L;sc=d.N;Y=d.O;Module._main=d.P;tc=d.Q;za=d.R;Ba=d.T;la=d.J;Tb=d.M;ka();return xc}var b={a:wc},c=Module.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});va??=Module.locateFile?Module.locateFile?Module.locateFile("jxl.wasm",ca):ca+"jxl.wasm":(new URL("jxl.wasm",import.meta.url)).href;return function(d){return a(d.instance)}(await ya(b))}());
await (async function(){qa();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));ha||(Module.noFSInit||cb||vb(),xc.K(),db=!1,Module.onRuntimeInitialized?.(),sa())}());;return Module}export default createJxlModule;
